Repository carsdotcom/cars-forge, pull requests merged in 2022-10, with the labels that each got.

#30 Added new badges to the Readme
  CHANGELOG.md
  README.md
Labels: hacktoberfest-accepted

#31 Added more clear SSH error message for improper credentials
  CHANGELOG.md
  src/forge/ssh.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#34 Add tests for yaml_loader.py to increase coverage
  .gitignore
  tests/test_yaml_loader.py
Labels: hacktoberfest-accepted

#35 Add tests for start.py
  src/forge/start.py
  tests/test_start.py
Labels: hacktoberfest-accepted

#36 Add venv to .gitignore
  .gitignore
Labels: hacktoberfest-accepted

#38 merge dev to main
  .bumpversion.cfg
  .gitignore
  CHANGELOG.md
  README.md
  pyproject.toml
  src/forge/__init__.py
  src/forge/common.py
  src/forge/create.py
  src/forge/destroy.py
  src/forge/main.py
  src/forge/rsync.py
  src/forge/ssh.py
  src/forge/start.py
  src/forge/yaml_loader.py
  tests/test_common.py
  tests/test_rsync.py
  tests/test_run.py
  tests/test_ssh.py
  tests/test_start.py
  tests/test_yaml_loader.py
Labels: hacktoberfest-accepted

#39 increase test coverage for forge/destory.py
  tests/test_destroy.py
Labels: enhancement, hacktoberfest-accepted
